### ISSUE TITLE
ANR appears when Interstitial ads are loaded?

### ISSUE THREAD

**Issue by leviLt** [googleads/googleads-mobile-android-examples#143]
```
at com.google.android.gms.ads.nonagon.b.a (b.java:5)
- waiting to lock <0x0ad82910> (a java.lang.Class<com.google.android.gms.ads.nonagon.b>) held by thread 22
  at com.google.android.gms.ads.nonagon.b.a (b.java:2)
  at com.google.android.gms.ads.nonagon.a.<init> (a.java:11)
  at com.google.android.gms.ads.ChimeraAdManagerCreatorImpl.newAdManagerByType (ChimeraAdManagerCreatorImpl.java:53)
  at com.google.android.gms.ads.internal.client.aq.a (aq.java:34)
  at com.bumptech.glide.load.model.AssetUriLoader.onTransact (AssetUriLoader.java:4)
  at android.os.Binder.transact (Binder.java:499)
  at cjd.a (cjd.java:2)
  at com.google.android.gms.ads.internal.client.q.newAdManagerByType (q.java)
  at com.google.android.gms.ads.AdManagerCreatorImpl.newAdManagerByType (AdManagerCreatorImpl.java:9)
  at com.google.android.gms.ads.internal.client.p.a (p.java:12)
  at cje.onTransact (cje.java:3)
  at android.os.Binder.transact (Binder.java:499)
  at com.google.android.gms.internal.ads.zzej.obtainAndWriteInterfaceToken (zzej.java)
  or                     .transactAndReadException (zzej.java)
  at com.google.android.gms.internal.ads.zzkw.zza (zzkw.java)
  at com.google.android.gms.internal.ads.zzjh.zza (zzjh.java)
  at com.google.android.gms.internal.ads.zzju.zzib (zzju.java)
  or                     .zza (zzju.java)
  at com.google.android.gms.internal.ads.zzjr$zza.zzid (zzjr.java)
  at com.google.android.gms.internal.ads.zzjr.zzhz (zzjr.java)
  or                     .zza (zzjr.java)
  at com.google.android.gms.internal.ads.zzma.zza (zzma.java)
  at com.google.android.gms.ads.InterstitialAd.loadAd (InterstitialAd.java)
  at com.cdtf.anInterstitial.AdmobInterstitial.LoadInterstitialWithContext (AdmobInterstitial.java:96)
  at com.cdtf.anInterstitial.InterstitialManagerItem.LoadInterstitial (InterstitialManagerItem.java:64)
  at com.cdtf.anInterstitial.InterstitialManagerItem.InitLoadInterstitial (InterstitialManagerItem.java:42)
  at com.cdtf.MainActivity.checkInitAndLoadInterstitialAd (MainActivity.java:568)
  at com.cdtf.MainActivity.onResume (MainActivity.java:544)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1279)
  at android.app.Activity.performResume (Activity.java:7017)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3611)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3676)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2876)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1567)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:156)
  at android.app.ActivityThread.main (ActivityThread.java:6585)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:831)
```
What's the problem?

**Comment by stowy** [comment]
Hi, thanks for reporting, this is a known issue and we will update when more information is available.

**Comment by scorpioLt** [comment]
Hi,What more information do you need ? We can provide.

**Comment by scorpioLt** [comment]
Hi,Today,We hava a new problem when Interstitial ads are loaded.
`
Fatal Exception: java.lang.OutOfMemoryErrorpthread_create (stack size 16384 bytes) failed: Try again Raw Text
--
  | java.lang.VMThread.create (VMThread.java)
  | java.lang.Thread.start (Thread.java:1029)
  | com.google.android.gms.internal.ads.zzbaf.zzaak (Unknown Source:11)
  | com.google.android.gms.internal.ads.zztq.a (Unknown Source:47)
  | com.google.android.gms.internal.ads.zztq.zzod (Unknown Source:24)
  | com.google.android.gms.ads.internal.zza.zzb (Unknown Source:65)
  | com.google.android.gms.internal.ads.zzzb.zza (Unknown Source:58)
  | com.google.android.gms.ads.InterstitialAd.loadAd (Unknown Source:9)
  | com.cdtf.anInterstitial.a.a (SourceFile:96)
  | com.cdtf.anInterstitial.f.a (SourceFile:64)
  | com.cdtf.anInterstitial.f.b (SourceFile:46)
  | com.cdtf.MainActivity.H (SourceFile:495)
  | com.cdtf.MainActivity.onResume (SourceFile:473)
  | android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1198)
  | android.app.Activity.performResume (Activity.java:5530)
  | android.app.ActivityThread.performResumeActivity (ActivityThread.java:3047)
  | android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3086)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)
  | android.os.Handler.dispatchMessage (Handler.java:102)
  | android.os.Looper.loop (Looper.java:136)
  | android.app.ActivityThread.main (ActivityThread.java:5586)
  | java.lang.reflect.Method.invokeNative (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:515)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
  | dalvik.system.NativeStart.main (NativeStart.java)

`

**Comment by stowy** [comment]
hi, the original ANR issue is fixed internally and will be rolled out in the next release, scheduled for next month. 

Regarding the latest issue you are having, can you please make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.  

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by out support team on the forum.

**Comment by EmmadHussain** [comment]
why do I keep getting notifications for this, I am in no way related to the
repo, I am not watching it and I have tried unsubscribe link (although I
never subscribed in first place), may be a bug in GitHub?

PS: I apologize for unrelated comment.
--
MI

**Comment by scorpioLt** [comment]
thanks

**Comment by scorpioLt** [comment]
Hi, Excuse me,Don't you know that the new version of the bug mentioned above has been fixed?

**Comment by abkoradiya** [comment]
Not Fixed still. I am facing ANR in new version **18.1.1**.

"main" prio=5 tid=1 Runnable | group="main" sCount=0 dsCount=0 obj=0x74fccf70 self=0xb3c05400 | sysTid=7151 nice=0 cgrp=default sched=0/0 handle=0xb6897534 | state=R schedstat=( 0 0 0 ) utm=94 stm=19 core=1 HZ=100 | stack=0xbe307000-0xbe309000 stackSize=8MB | held mutexes= "mutator lock"(shared held)
 at com.google.android.gms.internal.ads.zzcgv.zzakp (zzcgv.java:2)
 at com.google.android.gms.internal.ads.zzbeg.<init> (zzbeg.java:13)
 at com.google.android.gms.internal.ads.zzbeg.<init> (zzbeg.java:126)
 at com.google.android.gms.internal.ads.zzbeu.zzada (zzbeu.java:15)
 at com.google.android.gms.internal.ads.zzbds.zza (zzbds.java:19)
- locked <0x026f7378> (a java.lang.Class<com.google.android.gms.internal.ads.Qn>)
 at com.google.android.gms.internal.ads.zzbds.zzd (zzbds.java:10)
 at com.google.android.gms.internal.ads.zzbds.zza (zzbds.java:2)
 at com.google.android.gms.ads.internal.ClientApi.zzb (ClientApi.java:8)
 at com.google.android.gms.internal.ads.zzuf.zza (zzuf.java:12)
 at com.google.android.gms.internal.ads.zzul.zzod (zzul.java:25)
 at com.google.android.gms.internal.ads.zzul.zzd (zzul.java:51)
 at com.google.android.gms.internal.ads.zzww.zza (zzww.java:40)
 at com.google.android.gms.ads.InterstitialAd.loadAd (InterstitialAd.java:9)

**Comment by stowy** [comment]
@abkoradiya can you please file an issue in the [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help file an issue for this crash.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
