### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by shewenbiao** [googleads/googleads-mobile-android-examples#184]
ads sdk version: 17.2.1

There are many ooms in my project, the specific logs are as follows：

**Log1:**
```java
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
    at java.lang.Thread.nativeCreate(Native Method)
    at java.lang.Thread.start(Thread.java:1063)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
    at com.google.android.gms.ads.internal.util.future.ac.execute(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827)
    at com.google.android.gms.ads.nonagon.ad.activeview.b.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827:5)
    at com.google.android.gms.ads.internal.webview.j.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827:30)
    at com.google.android.gms.ads.internal.webview.ad.a(Unknown Source)
    at com.google.android.gms.ads.internal.webview.ae.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at aaj.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827)
    at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827:1)
    at aaj.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@20300004@20300004.251657827.251657827)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
**Log2:**
```java
java.lang.OutOfMemoryError: Failed to allocate a 98274 byte allocation with 57840 free bytes and 56KB until OOM
    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:185)
    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:63)
    at android.util.Base64.encodeToString(Base64.java:456)
    at org.chromium.android_webview.AwContents.a(PG:513)
    at com.android.webview.chromium.WebViewChromium.loadDataWithBaseURL(PG:278)
    at android.webkit.WebView.loadDataWithBaseURL(WebView.java:1131)
    at com.google.android.gms.ads.internal.webview.v.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827:37)
    at com.google.android.gms.ads.internal.webview.t.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827:14)
    at com.google.android.gms.ads.nonagon.ad.webview.c.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827:3)
    at com.google.android.gms.ads.nonagon.render.am.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827:12)
    at com.google.android.gms.ads.nonagon.render.an.a(Unknown Source)
    at com.google.android.gms.ads.internal.util.future.j.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:836)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at aaj.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827)
    at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827:1)
    at aaj.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@20300003@20300003.251657827.251657827)
    at android.os.Looper.loop(Looper.java:203)
    at android.app.ActivityThread.main(ActivityThread.java:6251)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
````

**Comment by stowy** [comment]
Thanks, this is a known issue and should be fixed in an upcoming release
scheduled for mid september.

**Comment by ramonaharrison** [comment]
Hi @stowy, are there any updates on a fix for this issue?

**Comment by stowy** [comment]
This should be fixed in a Play Services update in the next 2 weeks.

**Comment by codeerow** [comment]
Hey, @stowy! Still getting this issue in my project. Is this not solved yet?

**Comment by ajay-tilicho** [comment]
Hey, @stowy! We are still facing the issue. Is this not solved yet?

**Comment by JillSong** [comment]
We no longer support sdk version 17.2.1. Closing this issue as it's obsolete.
